spring:
  application:
    name: E-Management
  rsocket:
    server:
      port: 8080


  liquibase:
    change-log: db/changelog/changelog.xml
    enabled: true

  jpa:
    hibernate:
      use-new-id-generator-mappings: false
      ddl-auto: none
    properties:
      hibernate:
        enable_lazy_load_no_trans: true




  profiles:
    active: emanagement

jwt:
  key: publicStaticVoidMainString
