spring:
  application:
    name: E-Management


  liquibase:
    change-log: db/changelog/changelog.xml
    enabled: false

  jpa:
    hibernate:
      use-new-id-generator-mappings: false
      ddl-auto: update
#    properties:
#      hibernate:
#        enable_lazy_load_no_trans: true




  profiles:
    active: emanagement

jwt:
  key: publicStaticVoidMainString
server:
  port: 8090
