spring:
  datasource:
    url:  jdbc:sqlserver://103.94.159.179:1433;database=java
    username: dev
    password: sbdb@141
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
  jpa:
    show-sql: true
